### ISSUE TITLE
"Avoid portal" option text/tooltip/behavior mismatch

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#112]
Config > Lab > Options > "Avoid the portal if an exploration is visible..."

The tooltip says "if a treasure is visible" instead, which makes a lot more sense.  I suspect the behavior for this option IS based on Exploration paintings, though.  Best explanation for what I just saw it do, anyway -- repeatedly avoid the Portal (in defiance of the Priority tab), while an Exploration painting sat in the last row.  (There were no non-visible rows left.)

![image](https://user-images.githubusercontent.com/17887799/147584577-be5cab6f-27c5-449a-8b5c-df09e634497e.png)

P.S. Amazing piece of work, incredibly useful, great benefit for many people.  You have my deep respect.

**Comment by HughJeffner** [comment]
I took a look to be sure and it avoids the portal if any one of the 3 conditions are met:

- There's a treasure vault visible
- There's a explore painting visible
- There's more than 9 paintings remaining

Which I suppose I could make it more granular but I think it's fine the way it is.  Anyway I'll update the tooltip to be a bit more clear what the option does.

https://github.com/HughJeffner/FFRK-LabMem/blob/fb8b473957294247c824b7cd6e45621c66a51c4d/FFRK-LabMem/Machines/Lab.Actions.cs#L207

**Comment by slartifer** [comment]
I would advocate for cutting or separating the Exploration painting condition, personally.  You almost never want to pass up a Treasure painting, whatever your grinding goal is, whereas there aren't many goals where extra Explorations are crucial.  (If you just want to max out painting choices, Portal paintings would have a lower Priority than everything else anyway, and this setting wouldn't matter.)

Currently, I'm struggling with whether to check it or not -- in a setup like what I encountered (explore in back, portal in front and 6 green/orange combats in between) it was quite a waste.

**Comment by HughJeffner** [comment]
You make a good point, though personally when farming S1 I try to hit as many explores as I can.  A lot of times there's an easy to hit explore right behind the portal.

There really isn't a reason to bundle the three conditions together other than to keep it simple, and well, that cat is out of the bag.

**Comment by HughJeffner** [comment]
Alright, this will be split into three separate options (selected by default) in 6.4

**Comment by slartifer** [comment]
Sweet.  If there's a coffee fund that could use any contributions, let me know.

**Comment by HughJeffner** [comment]
This is now live in the latest release

Feel free to re-open if I missed something
