### ISSUE TITLE
Automatic offset not working correctly

### ISSUE THREAD

**Issue by Brandonspikes** [HughJeffner/FFRK-LabMem#124]
Tried both Nox and MuMu, no matter what I do it automatically sets the offset to t:40, b:1 no matter where I put the emulator, on either monitor, fullscreen or not, and yes I'm using 720x1280 in the emulator for screen size. I cleared it by setting it to -1 -1, and it still does t:40 b:1.

I tried with a second monitor and it still doesn't work, as well as just my single monitor

Then when I try to do the runs it opens my lab inventory, closes it, and says auto-start complete, and then just hangs without doing anything

Made a video demoing the problem.

https://www.youtube.com/watch?v=fFr2Eu6ZfJg

Edit: Moving the emulator, or even resizing it still gives me the same value every time

2nd Edit: Tried on a different computer, same offset value despite using a completely different setup and monitor resolution.

**Comment by Brandonspikes** [comment]
According to another user It's picking it up correctly and doing what its suppose to, but its just not starting the run, they're having the same issue I'm having

**Comment by HughJeffner** [comment]
Confirmed the special title screen is causing an issue
Will change the instructions to do this on the Home screen instead
