### ISSUE TITLE
Attempt auto-start before restarting?

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#125]
I've now caught a few "hangs" (that normally lead to the bot restarting FFRK) in the act, and in each case, the culprit was a display glitch (thanks WebView).  Additionally, in each case, triggering the bot auto-start (by manually disabling and re-enabling it) fixed the display glitch, and allowed the bot to proceed without restarting.

An option to **Attempt Auto-Start before resetting** could save a decent amount of time.  (Sadly, I don't think these are the cause of the fatal resets, where the device gets stuck on the passcode screen and the bot is helpless.)

**Comment by HughJeffner** [comment]
I am guessing the bot was in the `Ready` state (the screen with all the paintings and you select one)?

I could see an option where if the bot was in that state and the hang timer elapses (or maybe even half or 75% of the configured value) it could try to trigger an auto-start

**Comment by slartifer** [comment]
Sometimes; one of the ones I caught was on the Sealed Door screen (the prompt to open or ignore), and I suspect the same thing can happen on the treasure room chest selection screen.

**Comment by HughJeffner** [comment]
Oh they all have the 'check inventory' button.  I guess pretty much everywhere except starting, and in a battle.

**Comment by HughJeffner** [comment]
Got this included in the next release, 7.0
