### ISSUE TITLE
High capture rate may cause false-positive button finds

### ISSUE THREAD

**Issue by HughJeffner** [HughJeffner/FFRK-LabMem#142]
The button finding function may pick up buttons as they animate into place causing the tap to miss or not register.

Examples:

- When selecting a portal
- When selecting a combatant painting

Current mitigation is to add a delay so the animation completes first.  Possible fix is to tighten the color threshold as a valid button hit is < 1000 while invalid are frequently above.

**Comment by HughJeffner** [comment]
Maybe? I can try it.

Something like: add a new parameter to the button finding function where it has to find N consecutive identical or close enough matches

Only problem might be that minicap won't send a new frame if the screen hasn't changed so I will have to account for that somehow

**Comment by slartifer** [comment]
Is minicap vs ADB capturing relevant for bug reports, btw?  Mine's still on ADB, because LabMem crashes if I set it to minicap (and indeed it has to be manually edited in the config to get LabMem to stay open long enough to hit settings).

**Comment by HughJeffner** [comment]
In some cases, yeah.

I'm more interested in the minicap crash though.  Most of the speed improvements are from switching away from the very slow adb capture.  Feel free to open a new issue if you can provide any info on that.

**Comment by slartifer** [comment]
The window spits out a lot of text, but it closes after a split second, and it doesn't seem to leave any log behind.  I'll see if I can manage a screen cap on the window at all but that may be tricky.

**Comment by slartifer** [comment]
![image](https://user-images.githubusercontent.com/17887799/151244948-9b26fc0e-7d78-41dd-987a-79f2bb89e238.png)

Aha, here's the telling bit:

![image](https://user-images.githubusercontent.com/17887799/151244995-cb1ed422-8c2d-4350-bd0e-c6c138ce5d0f.png)

**Comment by HughJeffner** [comment]
The top of the trace is cut off but looks like a permissions error trying to write to `/data/local/tmp/`

What android device is this?

**Comment by slartifer** [comment]
Nox (debloated) > Samsung Galaxy S9+
Android 5

**Comment by slartifer** [comment]
Bigger capture

![image](https://user-images.githubusercontent.com/17887799/151253555-369c47b9-211a-4728-bda1-8df7948bd378.png)

**Comment by slartifer** [comment]
Enabling android > Security > "Allow installation of apps from unknown sources" and disabling > Developer options > "Verify apps over USB" (which calls out ADB app installation) had no impact

**Comment by HughJeffner** [comment]
Moving this discussion here: #154

**Comment by HughJeffner** [comment]
> Would it make any sense to just require 2 successive identical captures? That should give a good indication of whether an animation is in progress.

In regards to this, I have tested it and it seems to work.  Gonna test it on some other setups and see how it does.

**Comment by slartifer** [comment]
Here's a possible example of the actual issue here:

![image](https://user-images.githubusercontent.com/17887799/151368786-e156b5df-7904-48db-bfcd-825970912b11.png)

Hero inventory was not full.  Instead what was on the screen when the fault occured was the "the date has changed" dialogue.

**Comment by HughJeffner** [comment]
Was this during a lab restart?

**Comment by HughJeffner** [comment]
I applied the "2 match in a row" technique to several problem areas and it seems to have fixed the problem.  This will be added in 7.2.

I will handle other problem areas as they arise.

**Comment by slartifer** [comment]
> Was this during a lab restart?

Yes, the lab restart (with full inventory) happened to line up perfectly with the daily reset.  Orran would be proud.
