### ISSUE TITLE
Invalid state: when attempting recovery during BattleInfo

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#145]
Device showed the painting selection screen when found:

![image](https://user-images.githubusercontent.com/17887799/150911396-bec989f4-2d2b-41d7-a9a0-0fda16bd2bc8.png)

Looks like the painting selection may have gone too fast to register both taps.  Not sure.  I've set InterSelectPainting to 500 instead of 100 to see if this prevents future occurances.  (I notice the timings were all overwritten when I upgraded, too.)

**Comment by HughJeffner** [comment]
I have also seen it like this where it looks like got to the party equip screen.  Navigated back (which triggers a request through the proxy) then tried to auto-start while it was selecting the combatant painting again.

If you use the back button on the battle info screen it doesn't trigger a request, so the auto-start is needed

![image](https://user-images.githubusercontent.com/9453825/150993136-ac1e6930-2c73-4883-83ac-5bb3b69fce31.png)

**Comment by slartifer** [comment]
Just to note that InterSelectPainting of 500 did not prevent this from recurring:

![image](https://user-images.githubusercontent.com/17887799/151012235-635d76ac-a6b4-4e7d-b984-4d5edd5c02a3.png)

**Comment by HughJeffner** [comment]
BTW, you can have it take a screenshot when the 'Possible Hang' message appears with this option:

![image](https://user-images.githubusercontent.com/9453825/151033474-8e05d0e7-74d1-42b0-a168-eb03b0e9bf8d.png)

**Comment by HughJeffner** [comment]
Think I got this fixed in #148 

I will keep this open through the 7.1 release so you can add more reports if the issue persists

**Comment by slartifer** [comment]
Got one

![image](https://user-images.githubusercontent.com/17887799/151071821-7a63ce74-affa-4739-8ef8-2d7a4943a207.png)

![image](https://user-images.githubusercontent.com/17887799/151071851-f1d86dd1-d9db-46a0-895e-00974c45249e.png)

**Comment by HughJeffner** [comment]
The button is just gone huh?

**Comment by slartifer** [comment]
According to the snapshot.  I've never actually seen this myself -- I suspect the snapshot was truly taken mid-load.

**Comment by HughJeffner** [comment]
The bot disabling itself should be fixed in 7.1

I'll close this, but please reopen if the issue persists
