### ISSUE TITLE
Labmem jamming at the end of battles S3

### ISSUE THREAD

**Issue by ratatapa** [HughJeffner/FFRK-LabMem#170]
So randmly at the end of a battle in S3 Labmem will do the skip button then jam and dont press Next. which makes Labmem semi creash

If i press next manually then usually labmem is able to continue

**Comment by ratatapa** [comment]
post battle is 500

capture method is ADB at 200 MS

I never had this issue exept today when S3 started

**Comment by HughJeffner** [comment]
Whoops, I meant to ask for input method, adb or minitouch

**Comment by ratatapa** [comment]
Minitouch at 30 MS

09:23:09 Battle Info
09:23:16 Starting Battle
09:25:32 Battle Won! (01:57) Drop: 6* Dexterity Mote x1
09:26:32 Possible hang, attempting recovery!
09:26:32 Trying to auto-start
09:26:34 Could not auto-start
09:27:32 Restart loop detected!
09:27:32 Disabled Lab

**Comment by HughJeffner** [comment]
If using minitouch then I advise setting `Post-BattleButton` to the default of 2000ms as it continuously taps for the duration.

**Comment by ratatapa** [comment]
ill try it but i never changed the timers

**Comment by HughJeffner** [comment]
Maybe they changed something with that screen in S3?  Not sure

**Comment by ratatapa** [comment]
anyway the change seems fixed it didnt bug yet

**Comment by HughJeffner** [comment]
Alright, let me know if you have further issues
