### ISSUE TITLE
Restart counter decrements twice if FFRK crashes at lab completion

### ISSUE THREAD

**Issue by wilson91741** [HughJeffner/FFRK-LabMem#172]
If FFRK crashes on the lab completion screen and you have specified a number of times to repeat lab, the counter will decrement multiple times resulting in less runs being completed than expected.

![labmemrestartbug](https://user-images.githubusercontent.com/12853058/152663401-674b41e1-00ac-425c-858f-78407cd055a8.png)
e

**Comment by HughJeffner** [comment]
This will be fixed in 7.5 #176
