### ISSUE TITLE
7.4.0Beta timings seem off

### ISSUE THREAD

**Issue by mhelfrich78** [HughJeffner/FFRK-LabMem#173]
version 7.4.0Beta

Client seems to be ignoring "Move On" values under all conditions: exploration paintings, onslaught paintings,restoration paintings.  Client is waiting flat 10 seconds before clicking "Move on" (10,000 ms) no matter what values used. 

Client also seems to ignore timings for fatigue check, but insta battle has alleviated this mostly. except when the forced viewing of fatigue through "The enemy is upon you" is triggered. 

Did not seem to happen in prior versions.

**Comment by HughJeffner** [comment]
Are you using minicap/minitouch?  Any other android settings in the bot changed?

Also you can enable debug messages for timings to see exactly what the delay is

**Comment by mhelfrich78** [comment]
Ahh , using the debug tool, I was able to figure out that the ADB was causing the delay.  
I hadn't touched the capture/input methods   (Capture was set to adb, input was set to minitouch after update)

changing capture to minicap has fixed everything, and now the timings UI is reflected in actual timings ingame. 

Thanks for your help.  If this was in the helpsection or update notes, I missed it. 

This issue can be closed.
