### ISSUE TITLE
Detecting Android error messages?

### ISSUE THREAD

**Issue by slartifer** [HughJeffner/FFRK-LabMem#178]
Sometimes, when FFRK crashes, you get an error message like this one, which blocks all tap access to FFRK until it is dismissed:

![image](https://user-images.githubusercontent.com/17887799/153502081-8db9ce3f-fa7e-4033-9674-0dc637aa3881.png)

LabMem seems to be able to start FFRK without dismissing the error (thanks ADB), but it can't do anything past that.  I'm not sure if there's a way for the bot to detect the presence of an Android dialogue box.  Right now it just keeps going:

![image](https://user-images.githubusercontent.com/17887799/153503164-d0ba03ea-e798-46e4-8eba-1291ec7e92e5.png)

...which results, best case, in 1 unnecessary restart loop, but I've also returned to the device to find a sequence of 15 restarts stymied, as far as I can tell, by the dialogue box continuing to recur (or just never going away?  sometimes it goes away on the 2nd restart).

I haven't found any way to disable the error message (and I've been pretty aggressive about searching out possibly related settings and processes).

**Comment by HughJeffner** [comment]
It's built into AOSP and based on how many times and how recently it crashed if it shows up.  Apparently, it should self-dismiss itself in [5 minutes](https://github.com/aosp-mirror/platform_frameworks_base/blob/da6c7062c64b13ef435705c3aafe86e31f440e2f/services/core/java/com/android/server/am/AppErrorDialog.java#L57)

I wonder if just putting a "navigate back" command at the start of FFRK restart would dismiss it?

**Comment by slartifer** [comment]
This just happened again and I tried pressing the device back button -- it did successfully dismiss the error message!  So that should work, with the right timing.

**Comment by HughJeffner** [comment]
When does it appear, right after ffrk crashes?

I never see it on my device

**Comment by slartifer** [comment]
Fairly soon after a crash, but I'm not sure if it's immediate or takes a few seconds.  (I have seen this dialog on multiple devices.)

I don't know if the back button could ever do other things in a restarting-FFRK scenario (where this dialogue _isn't_ present).  If so, I wonder if it would be safer to address this as a contingency, i.e., only if FFRK reopens _and_ then fails to find or tap the Play button.

**Comment by HughJeffner** [comment]
I added the backspace in 7.5 #176 

Hopefully that resolves this issue, but please re-open this if it doesn't help.  I have a hard time trying to reproduce the conditions needed to test it.

**Comment by slartifer** [comment]
FYI, I think I observed part of this in action earlier tonight.  The device was in the "open apps" carousel (I assumed triggered by the backspace) and exited straight to FFRK when labmem fired the reopen.

The carousel might have been pulled up by the backspace being fired when there _wasn't_ an error dialogue.  Probably harmless enough, if that's all it can do.

**Comment by HughJeffner** [comment]
I tested pressing backspace in multiple areas and it didn't seem to have any effect on the home screen.  The open apps switcher is its own button so not sure how that got opened.

**Comment by slartifer** [comment]
Caught this again, and in-the-act:

![image](https://user-images.githubusercontent.com/17887799/154107833-fb85350f-3c3b-4f22-8317-5153446e664f.png)

It looks like my device just goes straight to the app carousel.  I think this may be a consequence of using Launcher Hijack (but if you also use that, maybe not).  Right after I took this, got "Crash Detected" and then the dialogue went away, presumably from the backspace.
