### ISSUE TITLE
Timed out waiting for fatigue values

### ISSUE THREAD

**Issue by hedrinjt** [HughJeffner/FFRK-LabMem#182]
I am having trouble with this part of the application. It doesn't seem to reliably gather information and select a team based on information.  I am running LabMem on Windows and running a fresh download of Memu.  Config for adb follows the information in the tutorial.  I am using the configuration in the WiFi settings to set the proxy address to the ip of my windows instance at port 8081.  I find usually it selects the team 2 regardless of fatigue.  I have tried multiple 'Use Party' options, currently using Lowest Fatigue (Any).  I think utilizing the Auto / Insta Battle would be OK to but I think that one says "not able to get fatigue values, picking manually" or something.  Would this be a proxy issue, or an adb issue or something else?

**Comment by HughJeffner** [comment]
Maybe it's a conflict with the the in-game setting for the party?  Try setting it to the default.

Neither of those are proxy or adb issues.  It has to do with how the game downloads and stores the fatigue info.  If they are downloaded while the bot isn't 'looking' the client won't download them again until after the next battle.  If that happens it shows that message and does a best guess on which party to use.

The other situation is when loading times are long, the bot waits for 20 seconds by default for them to download, if it times out then you get the warning message.  The timeout can be increased in the timings settings.

I think restarting the ffrk client and using auto/insta should work

**Comment by hedrinjt** [comment]
Sounds good, watching for a bit the auto/insta has been selecting selecting for a few minutes here.  thanks!
