### ISSUE TITLE
labmem error at start

### ISSUE THREAD

**Issue by tsukih** [HughJeffner/FFRK-LabMem#186]
Hello yesterday labmem was unable to do two portail in a raw whitout crashing so i decide to reinstall it from scratch this afternoon but it's  worse now . I cant lunch it at all  
![image](https://user-images.githubusercontent.com/96569841/156043261-438091c9-4ad7-4250-9ccd-fdd4b5b65500.png)
 i always face the same error 
 
 i try to reinstall the 7.4.0 version of labmem but i face the exact same issues
 
 do you have any idea of what i can do to solve this issues ?

**Comment by HughJeffner** [comment]
Can you post your `FFRK-LabMem.exe.Config` file?  Seems the problem is in there.

You can delete this file and re-run the installer and it should restore it to default.

**Comment by tsukih** [comment]
i try same issues 
here the file :
[FFRK-LabMem.exe.config.zip](https://github.com/HughJeffner/FFRK-LabMem/files/8156172/FFRK-LabMem.exe.config.zip)

**Comment by tsukih** [comment]
![image](https://user-images.githubusercontent.com/96569841/156052292-ab68678a-4516-438b-8216-5f664e1755b8.png)
look way better now ^^

**Comment by HughJeffner** [comment]
I put a fix in 7.6 #184 so it ignores the system regional setting when reading/writing config file to prevent this crash

Please re-open this if the issue persists
