### ISSUE TITLE
Labmem fails to start a new lab because "inventory is full", although this isn't the case

### ISSUE THREAD

**Issue by EirikDaude** [HughJeffner/FFRK-LabMem#189]
Pretty much what it says in the heading. This has happened to me a couple of times now, although it is by no means a regular occurence. 

Looking at my inventory I'm at 269/450 for Hero Artifacts, and nowhere close to full in any of the other inventory categories as far as I can see. Trying to start a lab by hand I do not get the error message for a full inventory category either.

As I mentioned, this is not a very common error I run across, but it would be nice if you could find the time to figure it out. If there is any further information I can give, please let me know.

**Comment by HughJeffner** [comment]
Can you post a screenshot of your party screen (after pressing the first 'enter' button)? Preferably with the same party members in the same slots as when the issue occurred.

Also, what are your android settings for find precision & accuracy?

**Comment by EirikDaude** [comment]
I think this is what you want a screenshot of? 
![bilde](https://user-images.githubusercontent.com/18211806/156242326-f2363604-ae6f-4739-b2a2-719c122a3702.png)

And these are the android settings (pretty sure they're the default):
![bilde](https://user-images.githubusercontent.com/18211806/156242553-8dd1ce57-1578-4aeb-add3-60bea7b50d12.png)

**Comment by HughJeffner** [comment]
Two more things if you could

What is your screen resolution in the emulator and what are your screen offsets in the bot general settings?

Thanks

**Comment by EirikDaude** [comment]
1120x700 and 34 (top) 35 (bottom)

**Comment by HughJeffner** [comment]
Okay thanks

I'll try to reproduce this tomorrow and will let you know what I find

**Comment by EirikDaude** [comment]
Thanks. Like I said, it only happens rarely, so dunno how easy it will be to reproduce. I haven't figured out any pattern to it myself...

But yeah, thanks a lot for taking a look at it 🙂

**Comment by HughJeffner** [comment]
Alright, a bit more thinking about this and I *think* I figured it out.  The culprit is this screen:

**Comment by HughJeffner** [comment]
Fixed in #184 

Please reopen if the issue persists after upgrading to 7.6
