### ISSUE TITLE
Wait for stamina fails if daily login reset happens during waiting period

### ISSUE THREAD

**Issue by wilson91741** [HughJeffner/FFRK-LabMem#198]
It appears if the daily login reset period happens while waiting for stamina, the bot will throw an error and disable itself.

![datechangebug](https://user-images.githubusercontent.com/12853058/158606800-40545a27-9b79-47bf-a1dd-518d20e501a9.png)
![datechangebug2](https://user-images.githubusercontent.com/12853058/158607866-5928bd15-5754-45cc-86c0-7fb67e026940.png)

**Comment by HughJeffner** [comment]
Not sure how but the `dungeon_recommend_info` url is requested during lab restart somehow.  Gonna try to reproduce this tonight with Lab and Proxy debug messages enabled.

I think just ignoring this transition would be a safe fix, already implemented in 7.7.1 #200

**Comment by HughJeffner** [comment]
Well, I couldn't replicate this but I think my fix should work.

Feel free to re-open if you get the same error in the upcoming 7.7.1 release.  It should be live in the next 24 hours.
