### ISSUE TITLE
.net framework error when entering lab mem config menu

### ISSUE THREAD

**Issue by ratatapa** [HughJeffner/FFRK-LabMem#201]
Hi the text is in french but when i press C in lab mem to go in the config it says 

The value -40 is not valid for Value.  Value Must be between minimum and Maximum

Parameter name : Value

Labmem version 7.7.0

**Comment by HughJeffner** [comment]
Hello

Can you post your `FFRK-LabMem.exe.Config` ?

The red stack trace might be helpful too if you can get it

**Comment by ratatapa** [comment]
<?xml version="1.0" standalone="yes"?>
<configuration>
  <appSettings file="AppSecrets.config">
    <add key="console.timestamps" value="true" />
    <add key="console.debugCategories" value="0" />
    <add key="console.logging" value="true" />
    <add key="adb.path" value="adb.exe" />
    <add key="adb.host" value="127.0.0.1:21503" />
    <add key="adb.closeOnExit" value="false" />
    <add key="proxy.port" value="8081" />
    <add key="proxy.secure" value="true" />
    <add key="proxy.blocklist" value="" />
    <add key="proxy.autoconfig" value="true" />
    <add key="proxy.connectionPooling" value="false" />
    <add key="lab.configFile" value=".\Config\lab.balanced.json" />
    <add key="lab.watchdogHangMinutes" value="3" />
    <add key="lab.watchdogCrashSeconds" value="30" />
    <add key="lab.watchdogMaxRetries" value="10" />
    <add key="lab.watchdogBattleMinutes" value="15" />
    <add key="lab.watchdogLoopDetectionThreshold" value="6" />
    <add key="lab.watchdogLoopDetectionWindowMinutes" value="60" />
    <add key="screen.topOffset" value="0" />
    <add key="screen.bottomOffset" value="1" />
    <add key="updates.checkForUpdates" value="true" />
    <add key="updates.includePrerelease" value="false" />
    <add key="datalogger.enabled" value="true" />
    <add key="counters.dropCategories" value="15" />
    <add key="counters.logDropsToTotal" value="false" />
    <add key="counters.materialsRarityFilter" value="6" />
    <add key="adb.capture" value="0" />
    <add key="adb.captureRate" value="200" />
    <add key="adb.tapDelay" value="30" />
    <add key="lab.watchdogHangSeconds" value="120" />
    <add key="lab.watchdogHangWarningSeconds" value="60" />
    <add key="lab.watchdogHangScreenshot" value="false" />
    <add key="lab.watchdogBattleMaxRetries" value="5" />
    <add key="adb.input" value="1" />
    <add key="adb.findPrecision" value="0,5" />
    <add key="adb.findAccuracy" value="0" />
    <add key="adb.tapDuration" value="0" />
    <add key="adb.tapPressure" value="50" />
    <add key="lab.watchdogHangWarningLoopThreshold" value="60" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
</configuration>

**Comment by ratatapa** [comment]
https://pastebin.com/CvqXxPAd

**Comment by HughJeffner** [comment]
I see it now.

Can you change this

`<add key="adb.findPrecision" value="0,5" />`

to this:

`<add key="adb.findPrecision" value="0.5" />`

I am guessing this happened after an upgrade from 7.5 or lower?

**Comment by ratatapa** [comment]
Thanks it worked and yeah i guess i was a lower version

**Comment by HughJeffner** [comment]
Okay

Version 7.6 and higher should save and read the config file in a region-independent format so you should be good now, unless you use a backed-up config file from version 7.5 or earlier
