### ISSUE TITLE
Any plan to add a filter for UE?

### ISSUE THREAD

**Issue by ratatapa** [HughJeffner/FFRK-LabMem#206]
Exemple open a treasure chest only if its a specific UE or it's impossible to achieve

**Comment by HughJeffner** [comment]
Unfortunately, it's not possible as we only know the [type of treasure](https://github.com/HughJeffner/FFRK-LabMem/tree/master/FFRK-LabMem/Config#treasure-types) before opening it, and the specific drop only after opening it.
