### ISSUE TITLE
Start lab from the dungeon corridor screens

### ISSUE THREAD

**Issue by alextcl** [HughJeffner/FFRK-LabMem#213]
At the moment, player will have to enter a corridor dungeon to trigger the state transition.
It will be great if the program could detect the enter button (similar to restart lab flow) and enter the dungeon automatically.

This could be one of the trying to auto start steps:
https://github.com/HughJeffner/FFRK-LabMem/blob/e24bbccf34a3385edc5664e96c07bc56ccb08c4b/FFRK-LabMem/Machines/Lab.Actions.cs#L71

**Comment by HughJeffner** [comment]
Added this in 7.9 #218
