### ISSUE TITLE
FFRK "System Error" Triggers Server Maintenance False Positive

### ISSUE THREAD

**Issue by wilson91741** [HughJeffner/FFRK-LabMem#214]
I noticed when running the bot today that I had a "system error" appear on FFRK that looks very similar to the server maintenance screen, and the bot appeared to believe there was an ongoing server maintenance and disabled itself with a scheduled restart for next daily login reset (when maintenance normally ends) 

![labmemsyserror](https://user-images.githubusercontent.com/12853058/164361867-e9158cb6-befb-43e7-aaea-5acaba8d9ec3.png)

**Comment by HughJeffner** [comment]
I tried various ways to trigger the system error in the client (random corruption of request/response, simulated 5xx responses) but couldn't figure it out.  I have not seen one of these occur naturally in the past few weeks either.

I'll have to wait until next maintenance so I can narrow down what elements are present for just the maintenance response.

**Comment by HughJeffner** [comment]
Ok, this should be fixed in 7.9.1 #221
