### ISSUE TITLE
Priority list not being followed.

### ISSUE THREAD

**Issue by OnSilverwings** [HughJeffner/FFRK-LabMem#226]
https://imgur.com/a/1WqhWG5

This has happened before but I wasn't able to catch it and it's never stopped my team from winning.  However, I thought I'd still being this up. For some reason Labmem in this instance picks the combat painting over exploration even though exploration is higher in the list. When I enabled Labmem it picked the combat painting again.  The painting turned out to be a forced Bahamut encounter and I have no battles set to avoid.

It doesn't seem to happen often but when it does it always happens for a given set.

**Comment by HughJeffner** [comment]
Do you happen to have the (now useless) 'avoid explore if treasure' enabled?

If you enable lab debug messages it should tell you the priority of each painting and if it was modified.

**Comment by OnSilverwings** [comment]
Ah, yes I did. It was greyed out and completely forgot this.
