### ISSUE TITLE
Stuck On Title Loading Screen

### ISSUE THREAD

**Issue by Xamnation29** [HughJeffner/FFRK-LabMem#227]
Got everything done up to loading the game up before setting screen offsets.

Infinitely stuck on title screen loading with the rotating circle and game constantly telling me "We're not able to connect. Please check your network settings and try again".

No port changing or anything I can imagine is stopping it from doing this.

**Comment by HughJeffner** [comment]
It's almost certainly a proxy issue

If you are using an emulator exclusively for FFRK I suggest using `Auto-configure device system proxy` in the bot proxy settings.  It makes sure everything is correct.  (If you need to revert this later you will have to press the `Reset system proxy` button in addition).

To verify the proxy is functional, in the general configuration settings there is `Show debug info`, click the drop-down and select `Proxy`.  Now open a browser in the emulator and you should see messages that traffic is passing.  Keep in mind the bot must be running for the emulator to have network connectivity.

One last thing is there is sometimes a bug where the `adb.exe` process holds open the proxy port even after the bot closes.  You can try one of these to fix that:

- Open task manager and kill `adb.exe` process
- Use `Close adb on exit` option in android settings of the bot
- Reboot your PC

**Comment by Xamnation29** [comment]
Seems like the auto configure worked, ty kind sir!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
