### ISSUE TITLE
LabMem aborts with a message that a maximum number of restarts had been reached

### ISSUE THREAD

**Issue by EirikDaude** [HughJeffner/FFRK-LabMem#231]
I don't know if you are going to keep maintaining this project, considering the EOS for the game is approaching, but I ran into a somewhat weird issue today.

Upon finishing a lab, LabMem aborted, with a message that a maximum number of restarts had been reached.

Looking at the log there had been no crashes in the previous hour or so, and I think the message when it aborts due to crashes is different as well.

I also checked the settings under lab for "Restart lab when completed" and "Use stamina potions", and both of those were checked.

Is this an user error where I've accidentally clicked some setting I don't know about, or something else?

![bilde](https://user-images.githubusercontent.com/18211806/177568744-ebc86131-324e-4ebf-a838-ec9fb8f733e4.png)

**Comment by EirikDaude** [comment]
Thanks for the response, and thanks for making this project available. The nature of the message made me suspect it may be something like that.

**Comment by HughJeffner** [comment]
No problem

I updated the readme with information about the EoS announcement
