### ISSUE TITLE
Weird Magic Pot/Fatigue related issue

### ISSUE THREAD

**Issue by Ratbacteria** [HughJeffner/FFRK-LabMem#77]
Hey Hugh,

Firstly thanks a bunch for this! Greatly appreciated! I think I ran across a bug related to the "Fatigue level check"
If the party fatigue is lower than the threshold then this happens:
![unknown](https://user-images.githubusercontent.com/94766838/142743669-700bce45-13dd-42ef-945a-bea2c99c44a1.png)
^ for clarity the party enters the battle at timestamp 17:08:50 but it's still checking for the fatigue popup when the party has killed the magic pot

From what I can tell it keeps looking for the second button (the warning that this party includes...) but the fight ends before the watchdog ends by itself. Only seems to happen on Magic Pot fights as those are fast whereas a normal fight will look like:
![unknown](https://user-images.githubusercontent.com/94766838/142743706-238573e3-9045-4e14-b24b-fce0773b2953.png)
^ for more clarity the party is already in battle at 17:12:09, it searches for a bit while the party is fighting then Watchdog kills the search and the battle concludes a short while later

When the party has higher fatigue then it's no problem:
![image](https://user-images.githubusercontent.com/94766838/142743922-da2f2b41-88ff-458e-ba68-e9b4e8f656a4.png)

Apologies if it's an issue on my end alone! :D 
Let me know if this info makes some sense!
Thanks again

**Comment by HughJeffner** [comment]
I made some changes in 5.1 to how the "in battle" state is determined that I _think_ should fix this.

Unfortunately my test machine is too slow to reproduce.  I should finalize the release in the next few days so you can test it and report back

**Comment by HughJeffner** [comment]
Please try the 5.1 release and report back, I think it should fix your issue.

**Comment by Ratbacteria** [comment]
I tried it yesterday and the case never happened (although it's happened to me 3-4x already in the past prior to the update haha)

The conditions are your fatigue needs to be lower than the threshold and you need to land on a magic pot, but from what I can see  with the current update it's not trying to find a button with watchdog while in battle anymore so it should have solved it.

Will update this post to confirm when I see if it fixed it :)

**Comment by HughJeffner** [comment]
Any other news on this?

I'm going to close this but feel free to re-open if needed

**Comment by Ratbacteria** [comment]
Your fix back in version 5.1 did in fact do it! Sorry never got around to closing the thread myself :)

Thanks again
