### ISSUE TITLE
Config settings reset.

### ISSUE THREAD

**Issue by OnSilverwings** [HughJeffner/FFRK-LabMem#94]
Updating from 5.30 to 5.6 resulted in the config settings resetting. It's not critical and something that can quickly be setup again.

**Comment by HughJeffner** [comment]
Using the setup installer right?

The .config file is set to only copy if it doesn't exist (missing values use defaults) and I didn't get this behavior in my tests.

Did it by chance get installed to a different directory somehow?

**Comment by OnSilverwings** [comment]
The trojan issue meant the auto install didn't work when I used alt+u. I tried to download it myself and then had to clear it with my antivirus software. I then used the fresh download to install so perhaps yes that overwrote the config file.

**Comment by HughJeffner** [comment]
So you extracted the .zip file then?

**Comment by OnSilverwings** [comment]
I believe I downloaded the exe, not the zip file.

**Comment by HughJeffner** [comment]
Hmm, that should have worked then since all the auto updater does is download and launch the very same file

**Comment by OnSilverwings** [comment]
Updated to 6.2 from previous version and the config settings didn't reset.
